---
version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
    - |
      echo Installing ASDF
      git clone https://github.com/asdf-vm/asdf.git "$HOME/.asdf" --branch v0.8.1
      . "$HOME/.asdf/asdf.sh"
      asdf version
    - |
      echo Installing ASDF plugins
      asdf plugin add terraform
      asdf plugin add terraform-docs
      asdf plugin add tflint
    - |
      echo Installing tools
      asdf install

  pre_build:
    commands:
    - echo "Terraform version:"
    - terraform -version

  build:
    commands:
    - make
